### ISSUE TITLE
Test call failed with an EPIPE error

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/clearwater-live-test#120]
#### Symptoms

```
Gemini - INVITE - Both reject, choose VoIP response (TCP) - (6505550066, 6505550077, 1236505550077@cw-ngv.com) Failed
Endpoint threw exception:
 - sip:6505550066@cw-ngv.com timed out waiting for 100
   - /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/quaff-0.7.3/lib/call.rb:205:in `rescue in recv_response'
   - /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/quaff-0.7.3/lib/call.rb:202:in `recv_response'
   - /home/ubuntu/clearwater-live-test/lib/tests/gemini.rb:621:in `block (2 levels) in <top (required)>'
Endpoint threw exception:
 - sip:6505550077@cw-ngv.com timed out waiting for new incoming call
   - /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/quaff-0.7.3/lib/endpoint.rb:65:in `rescue in incoming_call'
   - /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/quaff-0.7.3/lib/endpoint.rb:62:in `incoming_call'
   - /home/ubuntu/clearwater-live-test/lib/tests/gemini.rb:632:in `block (2 levels) in <top (required)>'
Endpoint threw exception:
 - sip:1236505550077@cw-ngv.com timed out waiting for new incoming call
   - /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/quaff-0.7.3/lib/endpoint.rb:65:in `rescue in incoming_call'
   - /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/quaff-0.7.3/lib/endpoint.rb:62:in `incoming_call'
   - /home/ubuntu/clearwater-live-test/lib/tests/gemini.rb:647:in `block (2 levels) in <top (required)>'
Failed
  Errno::EPIPE thrown:
   - Broken pipe - sendmsg(2)
     - /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/quaff-0.7.3/lib/sources.rb:46:in `sendmsg'
     - /home/ubuntu/.rvm/gems/ruby-1.9.3-p551/gems/quaff-0.7.3/lib/sources.rb:46:in `send_msg'
```

Rerunning the test worked.

#### Impact

Clearwater live tests are less reliable.

#### Release and environment 

Farfetch'd (release-99).

#### Steps to reproduce

Unknown.

**Comment by AlexHockey** [comment]
Is there a chance bono crashed during the test and broke the test's TCP connections?

**Comment by rkd-msw** [comment]
Ah - not crashed, but restarted. Effectively a dupe of https://github.com/Metaswitch/sprout/issues/1450.

**Comment by AlexHockey** [comment]
Cool. Looks like the live tests are doing their job then!
